### ISSUE TITLE
Client with higher ID does not update FD when accepting a connection

### ISSUE THREAD

**Issue by xit4** [lightem90/testMRMW#17]
When a client with lower ID (let's call it A) connects to a client with higher ID (let's call it B) it correctly updates the FD. On the other hand, when B is accepting A's connection, it does not update the FD (see picture)

Why? Because when B accepts a connection it only sees the remote IP:port of A, so it has no idea which ID connected.

![issue](https://cloud.githubusercontent.com/assets/7601720/12215405/96787f72-b6bb-11e5-8532-8b3068ff07c0.jpg)

As shown above B has no idea who /127.0.0.1:55483 is.
Do we need a "Hello" message right after connection to exchange IDs?

**Comment by lightem90** [comment]
Yeah and there's no way to know, from the accepter pow, the node ID of the connecting node. 
The algorithms we have doesn't give any specification about this.
The only solution that comes to my mind is that whenever a node connects if there it sees a majority of connected channels it makes a read operation (if there's no quorum it cannot read otherwise the read op will never complete and no other operations could be made). At that time the fd will be updated.
