### ISSUE TITLE
LE doesn't start on the node that creates quorum when connecting

### ISSUE THREAD

**Issue by xit4** [lightem90/testMRMW#8]
As shown in the picture below,
given 10 nodes, when node 6 connects a quorum is created so nodes 1-5 start a LE and elect 6 as their leader.
6 does NOT start the election until another node joins the system.
![](https://cloud.githubusercontent.com/assets/7601720/10431123/93240e70-7103-11e5-8085-62d8d55df5a9.png)

this is because election is started only after receiving end_handshake (so only on "old nodes") as seen at 
https://github.com/lightem90/testMRMW/blob/2cbf5ba6410e180a18aba6d2ab93691289f0dcdf/src/NetworkPrimitives/ConnectionManager.java#L241

Proposed solutions:
* move lines 
```java
if (n.getFD().getActiveNodes().size() >= n.getMySett().getQuorum() && n.getFD().getLeader_id() == -1)
    startElectionRoutine();
```
outside of `handleInit()`, probably in the main cycle in `run()`

* copy the same lines as previous point in the handling part of "init_ack" so that both the old node and the new node start the election as soon as quorum is reached
* start election somewhere else. Where?

**Comment by xit4** [comment]
temporarily fixed by using the first solution proposed in OP

**Comment by lightem90** [comment]
I think that we are wrong when handling a new connection. No problem if we call accept (maybe) but when we call finishConnect we should update the view in the right way and query the system, in this way every server up will have the updated view of every node every time a node connects to another one. (We can't do it now because read blocks). The sense of the "init" procedure was to make sure that every node had the updated view of every other node to correctly implement the leader election

**Comment by xit4** [comment]
leader election works properly now, if you don't consider issue #9
