### ISSUE TITLE
LE doesn't work when nodes start out of ID order

### ISSUE THREAD

**Issue by xit4** [lightem90/testMRMW#9]
given 10 nodes numbered from 1 to 10
if nodes start out of order, 1 2 3 4 6 5...
nodes 1 2 3 4 and 6 correctly elect 6 as master while node 5 elects itself as master.

**Comment by lightem90** [comment]
Because 5 doesn't put 6 in seemCrd because: or 5 doesn't have 6 correct view, or 6 view doesn't contain a quorum

**Comment by lightem90** [comment]
ok, I think that  the right way to implement correctly an handshake, in a way that the correct view and info about the leader are shared would be:

Remove the "init" message in the connect, this because we know who we are connecting to (fetching the id in the "othernodes" map), the connection is surely on because the key is connectable, we call finish connection and we can add the id directly (updating fd and communicate class).

Adding the "init" message in accept method. When the accepter calls accept it doesn't know the id of the connecting server (nor the port because is different) but it has a valid socketChannel where to write. So the init message is sent with the view (excluded the connecting node) and we may add informations about the leader. On the other hand the connecting client will receive a init with a wrong view (because itself WON'T be included in it, because the "accepter" doesn't know the id yet) but it can add himself easily and save it in replica and get informations about the leader (if present). At the end it will answer with "init_ack", in this way the "accepter" will be able to update FD, view and everything.

MAYBE a not blocking read would work as well (when connecting) without using init messages.

**Comment by lightem90** [comment]
Last issue is to make leader election work, imho it could be implemented using a read procedure everytime a server connects or everytime we accept a connection (in this case the key registered with OP_connected of that node should trigger). In this way views and replica map is always legit.

**Comment by xit4** [comment]
As discussed yesterday this issue is strictly linked to issue #8. Tests over all the proposed solutions of that issue, resulted in failures.
the latest try is this one
```java
if (handleInit(m)){
    //This must start as soon as we know a quorum is present
    if (n.getFD().getActiveNodes().size() >= n.getMySett().getQuorum() && n.getFD().getLeader_id() == -1)
        startElectionRoutine();
    parseInput(m, (SocketChannel) key.channel());
}
```
resulting in this
![issue](https://cloud.githubusercontent.com/assets/7601720/10544106/d5e4ecb8-7421-11e5-99df-f4f5f1c7e2de.png)

no election until the nodes receive a query message, which is never going to be received since only a leader can initiate a read/write.

I'm going to try and find a place for the Election to be started, maybe using the now unused return value of `handleInit()`

**Comment by lightem90** [comment]
a workaround would be to switch the default return value of handleInit 
default:
if (quorumIsPresent) return true //leads to LE
else return false //breaks and make it listen to more initMessages

BUT LE should be able to recognize by itself this case

**Comment by xit4** [comment]
the "counter" solution and the "return value" solution (proposed in my previous comment)
did not work due to the implementation of the cycle: variables cannot be instantiated and used in CM.run() nor in handleInit() because these functions are called once per message.

Exploring a solution for this election problem I found a [not so convincing part](https://github.com/lightem90/testMRMW/blob/3b1ab85de32b0b2c5d834420d2053abdc8563d05/src/electMasterService/electMasterService.java#L73): LE algorithm should use replicas in that part of the code and I'm not sure it does.

**Comment by lightem90** [comment]
have to go deeper in the paragraph 2.3 of LE paper. will do tomorrow

**Comment by lightem90** [comment]
Quoting:

It may happen that the system reaches a configuration with no coordinator. For example, this could be the case in the arbitrary configuration that the system starts in, or in the case that the coordinator of an installed view is no longer active. Each participant that detects that it has no coordinator, seeks for potential candidates based on the exchanged information. A processor p regards a processor q as a candidate, if q is active according to p’s failure detector, and there is a majority of processors that also think so (all these are based on p’s knowledge, which due to asynchrony might not be up to date). When there is more than one such candidate, processor p checks whether there is a candidate that has proposed a higher counter among the candidates. If there is one, then p considers it to be the coordinator and waits to hear from it (or learn that it is not active). If there is none, and based on its knowledge there is a majority of processors that also 
do not have a coordinator, then processor p acquires a counter from the counter increment algorithm and proposes a new view, with view ID, the counter, and group membership, the set of processors that appear active according to its failure detector. As we show, if p receives an “accept” message from all the processors in the view, then it proceeds to install the view, unless another processor who has obtained a higher counter does so. In a transition from one view to the next, there can be several processors attempting to become the coordinator (namely, those who according to their knowledge have a supporting majority). Still, by exploiting the intersection property of the supporting majorities we prove that each of these processors will propose a view at most once, and out of these, one view will be installed (i.e., we do not have never-ending attempts for new views to be installed).

**Comment by lightem90** [comment]
So, as far as I understand, we don't need to "updateReplica" or whatever else, just init messages to update FD. This is what I understand:
When a node comes online it tries to connect to higher id (not implemented atm) and sends init, when it receives the ack it updates its FD, its view and store the message in replica (with the current view of the other node, that could be "wrong" or "right").
When a quorum is present and no leader is detected (after the ack is sent, or after the ack is received because we shouldn't update the FD unless a message is received) everyone will check the informations they have in replica. Obviously all the "views" will be wrong (no updates) so nobody should be considered crd, so noCrd is detected. In this case the algorithm states that:
"If there is none, and based on its knowledge there is a majority of processors that also do not have a coordinator, then processor p acquires a counter from the counter increment algorithm and proposes a new view, with view ID, the counter, and group membership, the set of processors that appear active according to its failure detector." This is basically a write operation, with this everything would be solved because replica would be filled properly and the writer who actually completes the write would be the master (highest id, the fastest and so on).
The real problem is that our implementation doesn't support a write in which ALL the available nodes (or better, a majority of nodes) makes a write concurrently.

**Comment by lightem90** [comment]
added thread in last commit, things are not working because we probably have to change socketChannel into asynchronous socketchannel and other things. halp

**Comment by lightem90** [comment]
I changed some things in how the connection/disconnection is handled, hopefully in the right way. About the communicate thing, the only way it comes to my mind is to use my id as identifier together with the enum for the message type. Meaning: I send n query with myID/queryAck. And listen for messages that answer with myID/queryAck and so on (myID/prewriteack->myIDfinalize) When a quorum of this types of node is collected the function returns true (or false if the result is invalid). So it would be another field in Message class.
